### ISSUE TITLE
startsWith() and endsWith() methods

### ISSUE THREAD

**Issue by rogervila** [spatie/string#13]
Hello,

It would be nice to have `startsWith()` and `endsWith()` methods.

http://stackoverflow.com/questions/834303/startswith-and-endswith-functions-in-php

Are pull requests welcome?

**Comment by freekmurze** [comment]
You'll be glad to know that `startsWith` and `endsWith` are already provided through [the integration with `underscore.php`](https://github.com/spatie/string#integration-with-underscorephp)

https://github.com/Anahkiasen/underscore-php/blob/master/src/Methods/StringsMethods.php

**Comment by rogervila** [comment]
Nice to hear that. Thank you @freekmurze
