### ISSUE TITLE
[Feature Request] Callback on the result of the explode 

### ISSUE THREAD

**Issue by banstola** [spatie/string#20]
Hi,
Would it be a good idea to return `$this` from the `explode` and provide the possibility to use `array_filter` or `array_map` and other native feature on the array or simply a callback for the user defined action.

Usecase:

I have a string say 

```
$sizeStr = "Nice shoes with Size= 12 ,13, 14 , 15, "; 

$filterCallback= function($item){
return true; // just example 
};
$parsedSize = \string($sizeStr)
->lastSegment('Size=')
->trim()
->explode(',')
->arrayFilter()
->arrayMap('trim')
->apply(function($data){

});
```

Would something like this be useful ?

**Comment by freekmurze** [comment]
I think explode should return a regular array. Going to leave things as they are for now.
