### ISSUE TITLE
Is this typo?

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/string#27]
![image](https://user-images.githubusercontent.com/61916777/85949096-5a019c80-b987-11ea-968a-ced0b87a612c.png)

**Comment by freekmurze** [comment]
Not a typo

**Comment by lovecoding-git** [comment]
ahh,
It will replace a "a"  to "e" ?

Great, Thanks.

**Comment by freekmurze** [comment]
O, it is a typo, I didn't see the screenshot properly on my phone.

**Comment by freekmurze** [comment]
On third inspection it does seem correct, lol. Sorry for the confusion.

**Comment by lovecoding-git** [comment]
Great, Thank you!
